export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SET_PERSON_LIST = 'SET_PERSON_LIST';
export const SHOW_GET_DATA_BUTTON = 'SHOW_GET_DATA_BUTTON';
export const SHOW_PERSON_INFO_BLOCK = 'SHOW_PERSON_INFO_BLOCK';
